### ISSUE TITLE
Android platform configuration

### ISSUE THREAD

**Issue by ktfth** [appcelerator/node-appc#144]
[ERROR] Android Build Tools null are not supported by Titanium
[ERROR] Current installed Android SDK tools:
[ERROR]   Android SDK Tools:          26.1.1  (Supported: <=26.x)
[ERROR]   Android SDK Platform Tools: 28.0.1  (Supported: 28.x)
[ERROR]   Android SDK Build Tools:    not installed  (Supported: >=25.x <=28.x)
[ERROR]
[ERROR] Make sure you have the latest Android SDK Tools, Platform Tools, and Build Tools installed.
[ERROR]

Have a unique version on the developer site of android. Extra content appear when build tools added unnoficial.

Appcelerator Command-Line Interface, version 7.0.9
Copyright (c) 2014-2019, Appcelerator, Inc.  All Rights Reserved.

2019-01-02T12:33:31.870Z | ERROR  | An uncaught exception was thrown!
Invalid Version: zipalign.0.0
2019-01-02T12:33:31.871Z | ERROR  | Invalid Version: zipalign.0.0

What this can be mean?

**Comment by ewanharris** [comment]
Hey @ktfth, 

Could you possibly paste the full log of the command you're running? And if possible run with that command with `--log-level trace`.

**Comment by ktfth** [comment]
Appcelerator Command-Line Interface, version 7.0.9
Copyright (c) 2014-2019, Appcelerator, Inc.  All Rights Reserved.

2019-01-18T21:55:28.877Z | TRACE  | set environment to {"registry":"https://registry.platform.axway.com","baseurl":"https://platform.axway.com"}
2019-01-18T21:55:28.878Z | TRACE  | checking credentials for existing session
2019-01-18T21:55:28.975Z | TRACE  | Attempting to load session info from config file
2019-01-18T21:55:28.986Z | TRACE  | check if session is invalidated
2019-01-18T21:55:30.144Z | TRACE  | refresh session expiry to:  1548453330043
2019-01-18T21:55:30.147Z | TRACE  | session expiry 1548453330043 false
2019-01-18T21:55:30.149Z | TRACE  | Arrow Cloud config file: /home/ktfth/.acs
2019-01-18T21:55:30.154Z | TRACE  | found Arrow Cloud login { mid: 'da39a3ee5e6b4b0d3255bfef95601890afd80709',
  publishPort: 443,
  publishHost: 'https://admin.cloudapp-enterprise.appcelerator.com',
  username: 'kaeyosthaeron@gmail.com',
  cookie:
   [ 'connect.sid=s%3ASEzQf87AH0sdsxE8EGEHQkRPMGnZT0OQ.P7qeo0CBkg5atseqmVnftK03TH1KPf5eijvymzXUYFI; Path=/; Expires=Fri, 01 Feb 2019 21:54:47 GMT; HttpOnly' ],
  defaultEP:
   { publishHost: 'https://admin.cloudapp-enterprise.appcelerator.com',
     publishPort: 443 } } , checking nodeACSEndpoint= https://admin.cloudapp-enterprise.appcelerator.com
2019-01-18T21:55:30.155Z | TRACE  | Arrow Cloud cookie expiry [ 1549058087000 ]
2019-01-18T21:55:30.155Z | TRACE  | session already loaded in opts.session
2019-01-18T21:55:30.157Z | TRACE  | getCredentials() session:
{
  "ipaddress": "192.168.15.7",
  "username": "kaeyosthaeron@gmail.com",
  "password": "<OMITTED>",
  "session": "<OMITTED>",
  "nonce": "<OMITTED>",
  "environment": {
    "name": "production",
    "isProduction": true,
    "acsBaseUrl": "https://api.cloud.appcelerator.com",
    "acsAuthBaseUrl": "https://secure-identity.cloud.appcelerator.com",
    "nodeACSEndpoint": "https://admin.cloudapp-enterprise.appcelerator.com"
  },
  "token": "<OMITTED>",
  "fingerprint": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
  "fingerprint_description": "Linux with Mac Address: ",
  "org_id": 443517798732632,
  "expiry": 1548453330043
}
2019-01-18T21:55:30.157Z | TRACE  | loading plugins for command "run"
2019-01-18T21:55:30.170Z | TRACE  | run search paths:
[
  "/home/ktfth/.appcelerator/install/7.0.9/package",
  "/home/ktfth/.appcelerator/install/7.0.9/package/node_modules",
  "/home/ktfth/war/kitchensink-v2/plugins",
  "/home/ktfth/war/kitchensink-v2/node_modules",
  "/home/ktfth/war/node_modules",
  "/home/ktfth/node_modules",
  "/home/node_modules",
  "/node_modules",
  "/home/ktfth/.appcelerator/.npm/lib/node_modules"
]
2019-01-18T21:55:30.171Z | DEBUG  | [PLUGIN-LOAD] 0ms /home/ktfth/.appcelerator/install/7.0.9/package/appc.js
2019-01-18T21:55:30.360Z | DEBUG  | [PLUGIN-LOAD] 186ms /home/ktfth/.appcelerator/install/7.0.9/package/node_modules/appc-cli-titanium/appc.js
2019-01-18T21:55:30.360Z | DEBUG  | run plugin: /home/ktfth/.appcelerator/install/7.0.9/package/node_modules/appc-cli-titanium
2019-01-18T21:55:30.363Z | DEBUG  | [PLUGIN-LOAD] 1ms /home/ktfth/.appcelerator/install/7.0.9/package/node_modules/arrow/appc.js
2019-01-18T21:55:30.366Z | DEBUG  | run plugin: /home/ktfth/.appcelerator/install/7.0.9/package/node_modules/arrow
2019-01-18T21:55:30.394Z | TRACE  | plugin "arrow" failed its "when" function check, skipping...
2019-01-18T21:55:30.394Z | TRACE  | loading plugin "titanium" for command "run" CLI options via function
2019-01-18T21:55:30.396Z | TRACE  | loading plugin "titanium" for command "run" CLI options via array
2019-01-18T21:55:30.401Z | TRACE  | executing command "run" with the following plugins:
["titanium"]
2019-01-18T21:55:30.403Z | TRACE  | session already loaded in opts.session
2019-01-18T21:55:30.405Z | DEBUG  | Titanium Downloads Last Checked: 1547848488619
Target platform to build for:
 1)  android
Enter # or platform name: 1

2019-01-18T21:55:39.046Z | ERROR  | An uncaught exception was thrown!
Invalid Version: zipalign.0.0
2019-01-18T21:55:39.047Z | ERROR  | Invalid Version: zipalign.0.0
2019-01-18T21:55:39.047Z | TRACE  | TypeError: Invalid Version: zipalign.0.0
    at new SemVer (/home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/semver/semver.js:305:11)
    at Range.test (/home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/semver/semver.js:1112:15)
    at Function.satisfies (/home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/semver/semver.js:1161:16)
    at /home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/node-appc/lib/version.js:159:34
    at Array.some (<anonymous>)
    at Object.satisfies (/home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/node-appc/lib/version.js:155:36)
    at findSDK (/home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/node-titanium-sdk/lib/android.js:820:36)
    at /home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/node-titanium-sdk/lib/android.js:106:6
    at /home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/node-titanium-sdk/lib/android.js:89:5
    at /home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/async/dist/async.js:4096:9
---------------------------------------------
    at /home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/async/dist/async.js:118:9
    at _insert (/home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/async/dist/async.js:2250:13)
    at Object.push (/home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/async/dist/async.js:2303:13)
    at sdk (/home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/node-titanium-sdk/lib/android.js:103:10)
    at /home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/async/dist/async.js:3880:24
    at replenish (/home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/async/dist/async.js:1011:17)
    at /home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/async/dist/async.js:1041:24)
    at /home/ktfth/.titanium/mobilesdk/linux/7.5.0.GA/node_modules/async/dist/async.js:1046:16

**Comment by ewanharris** [comment]
@ktfth sorry for the delay getting back to you here, I think the problem might be down to a bad Android SDK path. Are you setting that yourself or is the SDK detecting it for you? The path should be something like `Users/eharris/Library/Android/Sdk/` where `add-ons`, `build-tools`, `platform-tools` are children of the dir
